- name: Add Mesosphere to Repository 
  become: yes
  apt_key: >
         keyserver=hkp://keyserver.ubuntu.com:80
         id=E56151BF
- shell: DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]'); CODENAME=$(lsb_release -cs); echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | tee /etc/apt/sources.list.d/mesosphere.list
  become: yes

- name: Install Prereq
  apt: >
     name={{ item }}
     force=yes
  become: yes
  with_items:
            - autoconf
            - libtool
            - build-essential
            - python-dev
            - python-boto
            - libcurl4-nss-dev
            - libsasl2-dev 
            - maven 
            - libapr1-dev 
            - libsvn-dev
            - git-all
            - python-pip

- name: Install Mesos
  apt: >
     name="mesos={{ mesosversion }}"
     update_cache=yes
     force=yes
  become: yes


- name:  Remove Zookeeper file
  file: >
     dest={{ zkfile }}
     state=absent
  become: yes

- name: Create Zookeeper file
  file: >
     dest={{ zkfile }}
     state=touch
  become: yes

- name: Assign Zookeeper address
  template: >
     src=zk
     dest={{ zkfile }}
  become: yes

- name: Setup JAVA_HOME for mesos
  become: yes
  lineinfile: >
      dest=/etc/default/mesos-slave
      line="{{ item }}"
  with_items: 
      - "JAVA_HOME={{ javahome }}"


- name: Add Docker to Repository 
  become: yes
  apt_key: >
         keyserver=hkp://p80.pool.sks-keyservers.net:80
         id=58118E89F3A912897C070ADBF76221572C52609D

- name: Get linux distro
  shell: cat /etc/*release | grep DISTRIB_CODENAME | awk -F'=' '{print $2}'
  register: dstro


- name: Add Docker to sources.list.d
  become: yes
  lineinfile: > 
      dest=/etc/apt/sources.list.d/docker.list
      line={{ item }}
      insertafter=EOF
      state=present
      create=yes
  with_items:
        - "deb https://apt.dockerproject.org/repo ubuntu-{{ dstro.stdout }}  main"

- name: Docker Engine
  apt: >
     name=docker-engine
     update_cache=yes
     force=yes
  become: yes


- name: Restart Docker
  become: yes
  service: > 
      name=docker
      state=restarted
